app/models.py
from sqlalchemy import ForeignKey
from app import db, login
from flask_login import UserMixin 
from datetime import datetime as dt, timedelta
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name =  db.Column(db.String)
    email =  db.Column(db.String, unique=True, index=True)
    password =  db.Column(db.String)
    created_on = db.Column(db.DateTime, default=dt.utcnow)

    def __repr__(self):
        return f'<User: {self.email} | {self.id}>'

    def __str__(self):
        return f'<User: {self.email} | {self.first_name} {self.last_name}>'

    def hash_password(self, original_password):
        return generate_password_hash(original_password)

    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)

    def from_dict(self, data):
        self.first_name = data['first_name']
        self.last_name = data['last_name']
        self.email=data['email']
        self.password = self.hash_password(data['password'])
        self.icon = data['icon']

    def save(self):
        db.session.add(self) 
        db.session.commit() 

    def to_dict(self):
        return {
            'id':self.id,
            'first_name':self.first_name,
            'last_name':self.last_name,
            'email':self.email,
            'created_on':self.created_on,
            'icon':self.icon,
            'is_admin':self.is_admin,
            'token':self.token
        }

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    description = db.Column(db.Text)
    price = db.Column(db.Float)
    img = db.Column(db.String)
    category_id = db.Column(db.Integer)
    created_on = db.Column(db.DateTime, index=True, default=dt.utcnow)

    def __repr__(self):
        return f'<Item: {self.id} | {self.name}>'

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def to_dict(self):
        item_data = {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "price": self.price,
            "img": self.img,
            "created_on": self.created_on
        }
        return item_data

    def from_dict(self, item_data):
        for field in ["name", "description", "price", "img",]:
            if field in item_data:
                setattr(self, field, item_data[field])

class Cart(db.Model):
    cart_id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, ForeignKey('user.id'))
    product_id = db.Column(db.Integer, ForeignKey('product.id'))





@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login = LoginManager()
db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class = Config):
    app = Flask(__name__,)
    app.config.from_object(config_class)

    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    login.login_view = 'auth.login'
    login.login_message = 'Please login, Trainer!'
    login.login_message_catergory='warning'

    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.blueprints.shop import bp as shop_bp
    app.register_blueprint(shop_bp)

    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import models, 

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='')

from . import routes

app/blueprints/main/routes.py
from flask import render_template
from . import bp as main

@main.route('/', methods = ['GET'])
# @login_required
def index():

    return render_template('index.html.j2')

app/blueprints/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__, url_prefix='')

from . import routes

app/blueprints/shop/routes.py
from flask import render_template, redirect, url_for, flash, request
from app.models import Product
from . import bp as shop

@shop.route('/shop', methods = ['GET', 'POST'])
# @login_required
def shop():
    products=Product.query.all()

    return render_template('shop.html.j2', products = products)

    

app/templates/base.html.j2
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    {# Internal CSS #}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <title>{% block title %} {% endblock %} - Top-Shelf Market Place</title>
  </head>

  <body>
  
  {# ------------ NavBar -------------- #}
    {% include './includes/nav.html.j2' %}
{# ------------ NavBar -------------- #}

{# ------------ Flash Message -------------- #}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for class, message in messages%}
                <div class="alert alert-{{class}} alert-dissimissble fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>    
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
{# ------------ Flash Message -------------- #}

    <section class="bg-dark text-white p-5 text-justify">
    {% block content %}
    {% endblock %}
    </section>

{# ------------ Footer -------------- #}
    {% include './includes/footer.html.j2' %}
{# ------------ Footer -------------- #}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/includes/footer.html.j2
<footer class="text-center text-dark bottom" style="background-color: #33b5e5;">
  <!-- Grid container -->
  <div class="container"></div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.0)">
    <p class="lead">&copy; Top-Shelf Market Place by DB-CAE89 2022</p>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/templates/includes/nav.html.j2
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Top-Shelf Market Place</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('shop.shop') }}">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      <span class="navbar justify-content-end">
            <a class="nav-link"  href="{{ url_for('auth.register') }}">Register</a>
            &nbsp; &nbsp; &nbsp;
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
      </span>
    </div>
  </div>
</nav>

app/templates/index.html.j2
{% extends 'base.html.j2' %}
{% block title %}
    Main
{% endblock %}

{% block content %}
  <section class="bg-dark text-white p-5 text-center">
    <div class="container">
      <div class="d-flex flex-column">
          <div class="p-4"><h1>Welcome to the <span class="text-info">Top-Shelf Market Place</span></h1></div>
          </div> 
      </div>
  </section>
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2' %}
{% block title %}
    Login
{% endblock %}

{% block content %}
<div class="container">
<div class="row align-items-center border border-info border-3 p-3">
<div class="col">
    <h1>Login</h1>
    <form action="{{ url_for('auth.login') }}", method="POST">
    
        {{form.hidden_tag()}}
        <div>
        {{ form.username.label(class="form-label") }}
        {{ form.username(class="form-control")}}
        {% for error in form.username.errors%}
            <small style="color:red"> {{ error }}</small>
        {% endfor%}
        </div>
        <br />
            <div>
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control")}}
            {% for error in form.password.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}
            </div>
            <br />
            <div>
            {{form.submit(class="btn btn-outline-info form-control")}}
            </div>
    </form>
    </div>
    </div>
    </div>
{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    {% if current_user.is_authenticated %}
        Edit Profile
    {% else %}
        Register
    {% endif %}
{% endblock %}

{% block content %}
<div class="border border-info border-3 p-3">
    <h1>
        {% if current_user.is_authenticated %}
            Edit Profile
        {% else %}
            Register
        {% endif %}
    </h1>
    
        <form action="{{url_for('auth.edit_prof') if current_user.is_authenticated else url_for('auth.register')}}", method = "POST">
            {{form.hidden_tag()}}

        <div>
            {{ form.first_name.label(class="form-label") }}
            {{ form.first_name(class="form-control", value=current_user.first_name)}}
            {% for error in form.first_name.errors%}
                <small style="color:red"> {{ error }}</small>
            {% endfor%}
        </div>
        <br />
        <div>
            {{ form.last_name.label(class="form-label") }}
            {{ form.last_name(class="form-control", value=current_user.last_name)}}
            {% for error in form.last_name.errors%}
                <small style="color:red"> {{ error }}</small>
            {% endfor%}
        </div>
        <br />
        <div>
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control")}}
            {% for error in form.email.errors%}
                <small style="color:red"> {{ error }}</small>
            {% endfor%}
        </div>
        <br />
        <div>
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control")}}
            {% for error in form.password.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}
        </div>
        <br />
        <div>
            {{form.confirm_password.label(class="form-label")}}
            {{form.confirm_password(class="form-control")}}
            {% for error in form.confirm_password.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}
        </div>
        <br />

        <div>
            {{form.submit(class="btn btn-outline-info form-control")}}
        </div>
        </form>
</div>
    
{% endblock %}

app/templates/shop.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    Shop
{% endblock %}

{% block content %}
 {% for item in products%}
  <div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
{% endfor %}
{% endblock %}